// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller"
application.register("insert-in-list", InsertInListController)

import ItineraryController from "./itinerary_controller"
application.register("itinerary", ItineraryController)

import LocationAutocompleteController from "./location_autocomplete_controller"
application.register("location-autocomplete", LocationAutocompleteController)

import check_all_checkboxes_controller from "./check_all_checkboxes_controller";
application.register("check-all-checkboxes", check_all_checkboxes_controller)

import MapController from "./map_controller"
application.register("map", MapController)
