// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import LocationAutocompleteController from "./location_autocomplete_controller";
application.register("location-autocomplete", LocationAutocompleteController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import ItineraryController from "./itinerary_controller";
application.register("itinerary", ItineraryController);

import MapController from "./map_controller";
application.register("map", MapController);


import check_all_checkboxes_controller from "./check_all_checkboxes_controller";
application.register("check-all-checkboxes", check_all_checkboxes_controller)
// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
